version: "3.8"

services:
  web:
    build: ./src
    image: fastapi_notes
    container_name: fastapi_notes
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8001:8000
